<a href="https://colab.research.google.com/github/rashmi05pathak/PRML_Data_Contest/blob/main/EE20S051_ED21S001_PRML_DataContest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pandas as pd
import numpy as np

In [ ]:
path1 = '/content/drive/MyDrive/PRML_Data Contest/Dataset_1_Training.csv'
path2 = '/content/drive/MyDrive/PRML_Data Contest/Dataset_2_Training.csv'
path3 = '/content/drive/MyDrive/PRML_Data Contest/Dataset_1_Testing.csv'
path4 = '/content/drive/MyDrive/PRML_Data Contest/Dataset_2_Testing.csv'

In [ ]:
####********Reading and preparing training data************######
training_data1 = pd.read_csv(path1)
training_data2 = pd.read_csv(path2)
#Converting to numpy array
training_data1_arr = training_data1.to_numpy() #working with 1st training data
training_data1_arr = training_data1_arr.transpose() 
training_data2_arr = training_data2.to_numpy()#working with 2nd training data
training_data2_arr = training_data2_arr.transpose() 

In [ ]:
X_train1 = training_data1_arr[1:,0:22283]
y_train_CO1 = training_data1_arr[1:,22283:22284]
y_train_CO1 = y_train_CO1.ravel()
y_train_CO1 = y_train_CO1.astype(int)

In [ ]:
y_train_CO2 = training_data1_arr[1:,22284:22285]
y_train_CO2 = y_train_CO2.ravel()
y_train_CO2 = y_train_CO2.astype(int)
print(y_train_CO2.shape)

(130,)


In [ ]:
X_train2 = training_data2_arr[1:,0:54675]
y_train_CO3 = training_data2_arr[1:,54675:54676]
y_train_CO3 = y_train_CO3.ravel()
y_train_CO3 = y_train_CO3.astype(int)
#print(y_train3.shape)

In [ ]:
#***CO4 output in training data*******#
y_train_CO4 = training_data2_arr[1:,54676:54677]
y_train_CO4 = y_train_CO4.ravel()
y_train_CO4 = y_train_CO4.astype(int)
#print(y_train4.shape)

In [ ]:
#***CO5 output in training data*******#
y_train_CO5 = training_data2_arr[1:,54677:54678]
y_train_CO5 = y_train_CO5.ravel()
y_train_CO5 = y_train_CO5.astype(int)
#print(y_train5.shape)

In [ ]:
#***CO6 output in training data*******#
y_train_CO6 = training_data2_arr[1:,54678:54679]
y_train_CO6 = y_train_CO6.ravel()
y_train_CO6 = y_train_CO6.astype(int)
#print(y_train6.shape)

In [ ]:
####********Reading and preparing Test data************######
testing_data1 = pd.read_csv(path3)
testing_data2 = pd.read_csv(path4)
testing_data1_arr = testing_data1.to_numpy()
testing_data2_arr = testing_data2.to_numpy()

In [ ]:
testing_data2.shape

(54675, 215)

In [ ]:
testing_data1_arr = testing_data1_arr.transpose()
X_test1 = testing_data1_arr[1:,0:22283]
testing_data2_arr = testing_data2_arr.transpose()
X_test2 = testing_data2_arr[1:,0:54675]

In [ ]:
def MCC_Score(TP,TN,FP,FN):
    import math
    val = (TP*TN)-(FP*FN)
    denom = (TP+FP)*(TP+FN)*(TN+FP)*(TN+FN)
    denom = math.sqrt(denom)
    return val/denom

In [ ]:
from sklearn.svm import LinearSVC
from sklearn.feature_selection import SelectFromModel
from sklearn.linear_model import LogisticRegression
#lsvc_CO1 = LinearSVC(C=0.01, penalty="l1", dual=False).fit(X_train1, y_train_CO1)
lsvc_CO1 = LogisticRegression(penalty='l2',C=0.001,random_state=0).fit(X_train1,y_train_CO1)

In [ ]:
model_CO1 = SelectFromModel(lsvc_CO1, prefit=True)
X_CO1_new = model_CO1.transform(X_train1)

In [ ]:
y_train_CO1.shape

(130,)

In [ ]:
#******Used for hyperparameter tuning*************************#
#from sklearn.model_selection import GridSearchCV
#from sklearn.ensemble import AdaBoostClassifier
#from sklearn.model_selection import cross_val_score
#grid = dict()
#grid['n_estimators'] = [10, 50, 100, 500]
#grid['learning_rate'] = [0.0001, 0.001, 0.01, 0.1, 1.0]
#grid['algorithm'] = ['SAMME', 'SAMME.R']


#grid_search = GridSearchCV(estimator=AdaBoostClassifier(), param_grid=grid, n_jobs=-1, cv=10, scoring='accuracy')
# execute the grid search
#grid_result = grid_search.fit(X_CO1_new, y_train_CO1)
# summarize the best score and configuration
#print("Best: %f using %s" % (grid_result.best_score_, grid_result.best_params_))



In [ ]:
#from sklearn.model_selection import train_test_split
#X_train_CO1, X_test_CO1, y_train_CO1_n, y_test_CO1_n = train_test_split(X_CO1_new, y_train_CO1, test_size=0.20, random_state=21)

In [ ]:
X_test_CO1.shape

(26, 8411)

In [ ]:
#from sklearn.ensemble import AdaBoostClassifier
#abc = AdaBoostClassifier(base_estimator=None, n_estimators=50, learning_rate=0.1,
#                         algorithm='SAMME', random_state=4)
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression(penalty='l2',C=0.001,random_state=0)

In [ ]:
clf = clf.fit(X_CO1_new,y_train_CO1)

In [ ]:
#*******Getting test data of shape of same as train data***********
arr_ind = model_CO1.get_support()
arr_ind.shape

(22283,)

In [ ]:
X_test_CO1_new = np.zeros((X_test1.shape[0],X_CO1_new.shape[1]))
j = 0
for i in range(arr_ind.shape[0]):
    if(arr_ind[i] == True):
      X_test_CO1_new[:,j] = X_test1[:,i]
      j = j+1

In [ ]:
y_pred_CO1 = clf.predict(X_test_CO1_new)

In [ ]:
y_pred_CO1

array([0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
##from sklearn.metrics import confusion_matrix
#c = confusion_matrix(y_test_CO1_n, y_pred_CO1)
#MCC_Score(c[1][1],c[0][0],c[0][1],c[1][0])

In [ ]:
#*********CO2*****************
from sklearn.svm import LinearSVC
from sklearn.feature_selection import SelectFromModel
lsvc_CO2 = LinearSVC(C=0.01, penalty="l1", dual=False).fit(X_train1, y_train_CO2)
model_CO2 = SelectFromModel(lsvc_CO2, prefit=True)
X_CO2 = model_CO2.transform(X_train1)

In [ ]:
#X_train_CO2, X_test_CO2, y_train_CO2, y_test_CO2 = train_test_split(X_CO2, y_train_CO2, test_size=0.20, random_state=21)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf_Model_2 = RandomForestClassifier(n_estimators=17, criterion='gini', max_depth=4,
                                  min_samples_split=2, min_samples_leaf=2,
                                  min_weight_fraction_leaf=0.0, max_features='sqrt',
                                  max_leaf_nodes=None, min_impurity_decrease=0.0,
                                  bootstrap=False, oob_score=False, n_jobs=None, random_state=4, verbose=0,
                                  warm_start=False, class_weight=None, ccp_alpha=0.0, max_samples=None)

In [ ]:
rf_Model_2 = rf_Model_2.fit(X_CO2,y_train_CO2)

In [ ]:
#*******Getting test data of shape of same as train data***********
arr_ind = model_CO2.get_support()
arr_ind.shape

(22283,)

In [ ]:
X_test_CO2_new = np.zeros((X_test1.shape[0],X_CO2.shape[1]))
j = 0
for i in range(arr_ind.shape[0]):
    if(arr_ind[i] == True):
      X_test_CO2_new[:,j] = X_test1[:,i]
      j = j+1

In [ ]:
y_pred_CO2 = rf_Model_2.predict(X_test_CO2_new)

In [ ]:
y_pred_CO2

array([1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0])

In [ ]:
#from sklearn.metrics import confusion_matrix
#c = confusion_matrix(y_test_CO2, y_pred_CO2)
#MCC_Score(c[1][1],c[0][0],c[0][1],c[1][0])

In [ ]:
#********CO3************#####
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
lg3 = LogisticRegression(C = 0.001,penalty = 'l2',random_state = 4)
#lsvc_CO3 = LinearSVC(C=0.01, penalty="l1", dual=False).fit(X_train2, y_train_CO3)
model_CO3 = SelectFromModel(lg3).fit(X_train2,y_train_CO3)
X_CO3 = model_CO3.transform(X_train2)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [ ]:
X_CO3.shape

(340, 21017)

In [ ]:
#******Used for hyperparameter tuning*************************#
#from sklearn.model_selection import GridSearchCV
#from sklearn.linear_model import LogisticRegression
#from sklearn.model_selection import cross_val_score
#grid = dict()
#grid['penalty'] = ['l1', 'l2', 'elasticnet', 'none']
#grid['C'] = [0.0001, 0.001, 0.01, 0.1, 1.0]
#grid['algorithm'] = ['SAMME', 'SAMME.R']


#grid_search = GridSearchCV(estimator=LogisticRegression(), param_grid=grid, n_jobs=-1, cv=10, scoring='accuracy')
# execute the grid search
#grid_result = grid_search.fit(X_CO3, y_train_CO3)
# summarize the best score and configuration
#print("Best: %f using %s" % (grid_result.best_score_, grid_result.best_params_))

In [ ]:
y_train_CO3.shape

(340,)

In [ ]:
#from sklearn.model_selection import train_test_split
#X_train_CO3, X_test_CO3, y_train_CO3_n, y_test_CO3 = train_test_split(X_CO3, y_train_CO3, test_size=0.20, random_state=21)

In [ ]:
#lsvc_CO3 = LinearSVC(C=0.01, penalty="l1", dual=False).fit(X_train_CO3, y_train_CO3)

In [ ]:
#rf_Model_3 = RandomForestClassifier(n_estimators=17, criterion='gini', max_depth=2,
 #                                 min_samples_split=2, min_samples_leaf=1,
 #                                 max_features='auto',bootstrap=False,random_state = 4)

In [ ]:
lg3 = LogisticRegression(C = 1.0,penalty = 'l2',random_state = 4)

In [ ]:
lg3 = lg3.fit(X_CO3,y_train_CO3)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [ ]:
#*******Getting test data of shape of same as train data***********
arr_ind = model_CO3.get_support()
arr_ind.shape

(54675,)

In [ ]:

X_test_CO3_new = np.zeros((X_test2.shape[0],X_CO3.shape[1]))
j = 0
for i in range(arr_ind.shape[0]):
    if(arr_ind[i] == True):
      X_test_CO3_new[:,j] = X_test2[:,i]
      j = j+1

In [ ]:
y_pred_CO3 = lg3.predict(X_test_CO3_new)

In [ ]:
y_pred_CO3

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0])

In [ ]:
#from sklearn.metrics import confusion_matrix
#c = confusion_matrix(y_test_CO3, y_pred_CO3)
#MCC_Score(c[1][1],c[0][0],c[0][1],c[1][0])

0.8563596509947511

In [ ]:
#from sklearn.metrics import matthews_corrcoef
#matthews_corrcoef(y_test_CO3, y_pred_CO3)

0.8563596509947511

In [ ]:
X_test_CO3_new.shape
#**************************************************************

(214, 62)

In [ ]:
from sklearn.svm import LinearSVC
from sklearn.feature_selection import SelectFromModel
rf_Model_4 = RandomForestClassifier(n_estimators=10, max_depth=4,
                                    min_samples_split=5, min_samples_leaf=2,
                                    max_features='sqrt',bootstrap=False,random_state = 42).fit(X_train2,y_train_CO4)

In [ ]:
model_CO4 = SelectFromModel(rf_Model_4, prefit=True)
X_CO4_new = model_CO4.transform(X_train2)

In [ ]:
#model_CO4.get_support()

(54675,)

In [ ]:
#********CO4************#####
#lsvc_CO4 = LinearSVC(C=0.01, penalty="l1", dual=False).fit(X_train2, y_train_CO4)
#rf_Model_4 = RandomForestClassifier(n_estimators=10, max_depth=4,
#                                  min_samples_split=5, min_samples_leaf=2,
#                                  max_features='sqrt',bootstrap=False,random_state = 42)
#model_CO4 = SelectFromModel(rf_Model_4).fit(X_train2,y_train_CO4)
#X_CO4 = model_CO4.transform(X_train2)


In [ ]:
#X_train_CO4, X_test_CO4, y_train_CO4_n, y_test_CO4_n = train_test_split(X_CO4, y_train_CO4, test_size=0.20, random_state=21)

In [ ]:
#from sklearn.model_selection import GridSearchCV
##from sklearn.ensemble import AdaBoostClassifier
#grid = dict()
#grid['n_estimators'] = [10, 50, 100, 500]
#grid['learning_rate'] = [0.0001, 0.001, 0.01, 0.1, 1.0]
##grid['algorithm'] = ['SAMME', 'SAMME.R']


#grid_search = GridSearchCV(estimator=AdaBoostClassifier(), param_grid=grid, n_jobs=-1, cv=10, scoring='accuracy')
# execute the grid search
#grid_result = grid_search.fit(X_train_CO4, y_train_CO4_n)
# summarize the best score and configuration
#print("Best: %f using %s" % (grid_result.best_score_, grid_result.best_params_))



Best: 0.860185 using {'algorithm': 'SAMME', 'learning_rate': 1.0, 'n_estimators': 100}


In [ ]:
rf_Model_4 = RandomForestClassifier(n_estimators=10, max_depth=4,
                                   min_samples_split=5, min_samples_leaf=2,
                                   max_features='sqrt',bootstrap=False,random_state = 42)

In [ ]:
rf_Model_4 = rf_Model_4.fit(X_CO4_new,y_train_CO4)

In [ ]:
#*******Getting test data of shape of same as train data***********
arr_ind_CO4 = model_CO4.get_support()
#arr_ind.shape

X_test_CO4_new = np.zeros((X_test2.shape[0],X_CO4_new.shape[1]))
j = 0
for i in range(arr_ind_CO4.shape[0]):
    if(arr_ind_CO4[i] == True):
      X_test_CO4_new[:,j] = X_test2[:,i]
      j = j+1

In [ ]:
y_pred_CO4 = rf_Model_4.predict(X_test_CO4_new)

In [ ]:
y_pred_CO4 #Isko improve karna hai

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
#c = confusion_matrix(y_test_CO4_n, y_pred_CO4)
#MCC_Score(c[1][1],c[0][0],c[0][1],c[1][0])

0.3098898934004561

In [ ]:
#********CO5************************
#rf_Model_5 = RandomForestClassifier(n_estimators=72, max_depth=4,
#                                  min_samples_split=5, min_samples_leaf=1,
#                                  max_features='sqrt',bootstrap=False,random_state = 4)
from sklearn.ensemble import AdaBoostClassifier
abc5 = AdaBoostClassifier(base_estimator=None, n_estimators=100, learning_rate=1.0,
                          algorithm='SAMME.R', random_state=42)
model_CO5 = SelectFromModel(abc5).fit(X_train2,y_train_CO5)
X_CO5 = model_CO5.transform(X_train2)

In [ ]:
#X_train_CO5, X_test_CO5, y_train_CO5, y_test_CO5 = train_test_split(X_CO5, y_train_CO5, test_size=0.20, random_state=21)

In [ ]:
#rf_Model_5 = RandomForestClassifier(n_estimators=72, max_depth=4,
#                                  min_samples_split=5, min_samples_leaf=1,
#                                  max_features='sqrt',bootstrap=False,random_state = 4)

In [ ]:
abc5 = AdaBoostClassifier(base_estimator=None, n_estimators=100, learning_rate=1.0,
                          algorithm='SAMME.R', random_state=42)

In [ ]:
 #*******Getting test data of shape of same as train data***********
arr_ind = model_CO5.get_support()
arr_ind.shape

X_test_CO5_new = np.zeros((X_test2.shape[0],X_CO5.shape[1]))
j = 0
for i in range(arr_ind.shape[0]):
    if(arr_ind[i] == True):
      X_test_CO5_new[:,j] = X_test2[:,i]
      j = j+1

In [ ]:
abc5 = abc5.fit(X_CO5,y_train_CO5)
y_pred_CO5 = abc5.predict(X_test_CO5_new)


In [ ]:
y_pred_CO5

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0])

In [ ]:
#c = confusion_matrix(y_test_CO5, y_pred_CO5)
#MCC_Score(c[1][1],c[0][0],c[0][1],c[1][0])

0.8927543800512034

In [ ]:
#***********CO6******************
from sklearn.svm import LinearSVC
from sklearn.feature_selection import SelectFromModel
#lsvc = LinearSVC(C=0.01, penalty="l1", dual=False).fit(X_train2, y_train_CO6)
rf_Model_6 = RandomForestClassifier(n_estimators=25, max_depth=4,
                                  min_samples_split=2, min_samples_leaf=2,
                                  max_features='sqrt',bootstrap=False,random_state = 4)
model = SelectFromModel(rf_Model_6).fit(X_train2,y_train_CO6)
X_new = model.transform(X_train2)

In [ ]:
X_new.shape

(340, 79)

In [ ]:
y_train_CO6.shape

(340,)

In [ ]:
#from sklearn.model_selection import train_test_split
#X_train_CO6, X_test_CO6, y_train_CO6, y_test_CO6 = train_test_split(X_new, y_train_CO6, test_size=0.20, random_state=21)

In [ ]:
X_train_CO6.shape

(272, 79)

In [ ]:
X_train2.shape

(340, 54675)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf_Model_6 = RandomForestClassifier(n_estimators=25, max_depth=4,
                                  min_samples_split=2, min_samples_leaf=2,
                                  max_features='sqrt',bootstrap=False,random_state = 4)

In [ ]:
 #*******Getting test data of shape of same as train data***********
arr_ind = model.get_support()
arr_ind.shape

X_test_CO6_new = np.zeros((X_test2.shape[0],X_new.shape[1]))
j = 0
for i in range(arr_ind.shape[0]):
    if(arr_ind[i] == True):
      X_test_CO6_new[:,j] = X_test2[:,i]
      j = j+1

In [ ]:
rf_Model_6 = rf_Model_6.fit(X_new,y_train_CO6)

In [ ]:
y_pred_CO6 = rf_Model_6.predict(X_test_CO6_new)

In [ ]:
y_pred_CO6

array([1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1])

In [ ]:
#from sklearn.metrics import confusion_matrix
#c = confusion_matrix(y_test_CO6, y_pred_CO6)
#MCC_Score(c[1][1],c[0][0],c[0][1],c[1][0])

0.24159717180424753

In [ ]:
#from sklearn.metrics import accuracy_score
#accuracy_score(y_test_CO6, y_pred_CO6)

0.6176470588235294

In [ ]:
X_test2.shape

(214, 54675)

In [ ]:
arr = np.concatenate((y_pred_CO1,y_pred_CO2,y_pred_CO3,y_pred_CO4,y_pred_CO5,y_pred_CO6),axis = 0)
d = {'Predicted':arr}
index = []
for i in range(0,1056):
    index.append(i)
df = pd.DataFrame(data = d)
df.insert(0,'Id',index)
df.to_csv('JayHo3.csv',index=False)